import type { OnboardingQuestionDto } from '@/types/domain/onboardingCatalog.types';

/** Offline fallback when auth does not use the backend — mirrors DB seed shape. */
export const MOCK_ONBOARDING_CATALOG: OnboardingQuestionDto[] = [
  {
    stepKey: 'purpose',
    kind: 'single',
    sortOrder: 1,
    heroEmoji: '✨',
    title: 'What are you here for?',
    subtitle: 'We’ll tune who you see first',
    minSelections: null,
    maxSelections: null,
    options: [
      { key: 'dating', label: 'Dating', hint: 'Serious relationship & chemistry', emoji: '❤️', sortOrder: 1 },
      { key: 'friendship', label: 'Friendship', hint: 'Good energy & new friends', emoji: '🤝', sortOrder: 2 },
      { key: 'both', label: 'Both', hint: 'Open to anything real', emoji: '💫', sortOrder: 3 },
    ],
  },
  {
    stepKey: 'age_preference',
    kind: 'single',
    sortOrder: 2,
    heroEmoji: '💫',
    title: 'Preferred age range?',
    subtitle: 'Choose one age range you’re open to',
    minSelections: null,
    maxSelections: null,
    options: [
      { key: '18-24', label: '18–24', hint: 'Younger crowd', emoji: '🌸', sortOrder: 1 },
      { key: '25-29', label: '25–29', hint: 'Mid-twenties', emoji: '🌿', sortOrder: 2 },
      { key: '30-34', label: '30–34', hint: 'Early thirties', emoji: '☀️', sortOrder: 3 },
      { key: '35-39', label: '35–39', hint: 'Late thirties', emoji: '🍷', sortOrder: 4 },
      { key: '40-44', label: '40–44', hint: 'Forties', emoji: '🎩', sortOrder: 5 },
      { key: '45+', label: '45+', hint: 'Mature matches', emoji: '🥂', sortOrder: 6 },
      { key: 'open-all', label: 'Open to all ages', hint: 'Age doesn’t matter', emoji: '🌍', sortOrder: 7 },
    ],
  },
  {
    stepKey: 'interested_in',
    kind: 'single',
    sortOrder: 3,
    heroEmoji: '💕',
    title: 'Who are you interested in?',
    subtitle: 'Choose who you’d like to meet',
    minSelections: null,
    maxSelections: null,
    options: [
      { key: 'men', label: 'Men', hint: 'Interested in men', emoji: '👨', sortOrder: 1 },
      { key: 'women', label: 'Women', hint: 'Interested in women', emoji: '👩', sortOrder: 2 },
      { key: 'nonbinary', label: 'Non-binary', hint: 'Beyond the binary', emoji: '🌈', sortOrder: 3 },
      { key: 'everyone', label: 'Everyone', hint: 'Open to all genders', emoji: '💫', sortOrder: 4 },
    ],
  },
  {
    stepKey: 'orientation',
    kind: 'single',
    sortOrder: 4,
    heroEmoji: '🌈',
    title: 'How do you identify?',
    subtitle: 'Optional — helps us personalize your experience',
    minSelections: null,
    maxSelections: null,
    options: [
      { key: 'straight', label: 'Straight', hint: 'Attracted to another gender', emoji: '💑', sortOrder: 1 },
      { key: 'gay', label: 'Gay', hint: 'Men attracted to men', emoji: '🏳️‍🌈', sortOrder: 2 },
      { key: 'lesbian', label: 'Lesbian', hint: 'Women attracted to women', emoji: '💜', sortOrder: 3 },
      { key: 'bisexual', label: 'Bisexual', hint: 'More than one gender', emoji: '💗', sortOrder: 4 },
      { key: 'pansexual', label: 'Pansexual', hint: 'Hearts over labels', emoji: '💛', sortOrder: 5 },
      { key: 'queer', label: 'Queer', hint: 'Fluid & expansive', emoji: '🌈', sortOrder: 6 },
      { key: 'prefer-not-to-say', label: 'Prefer not to say', hint: 'Totally fine', emoji: '🤐', sortOrder: 7 },
    ],
  },
  {
    stepKey: 'religion',
    kind: 'single',
    sortOrder: 5,
    heroEmoji: '🕊️',
    title: 'Faith or worldview?',
    subtitle: 'Used for better compatibility insights',
    minSelections: null,
    maxSelections: null,
    options: [
      { key: 'christian', label: 'Christian', hint: 'Christian faith', emoji: '✝️', sortOrder: 1 },
      { key: 'muslim', label: 'Muslim', hint: 'Islamic faith', emoji: '☪️', sortOrder: 2 },
      { key: 'hindu', label: 'Hindu', hint: 'Hindu traditions', emoji: '🕉️', sortOrder: 3 },
      { key: 'buddhist', label: 'Buddhist', hint: 'Buddhist path', emoji: '☸️', sortOrder: 4 },
      { key: 'jewish', label: 'Jewish', hint: 'Jewish heritage', emoji: '✡️', sortOrder: 5 },
      { key: 'spiritual', label: 'Spiritual', hint: 'Not tied to one religion', emoji: '✨', sortOrder: 6 },
      { key: 'agnostic', label: 'Agnostic', hint: 'Unsure about faith', emoji: '🤔', sortOrder: 7 },
      { key: 'atheist', label: 'Atheist', hint: 'Secular worldview', emoji: '🌌', sortOrder: 8 },
      { key: 'other', label: 'Other', hint: 'Something else', emoji: '📿', sortOrder: 9 },
      { key: 'prefer-not-to-say', label: 'Prefer not to say', hint: 'Skip for now', emoji: '🤐', sortOrder: 10 },
    ],
  },
  {
    stepKey: 'interests',
    kind: 'multi',
    sortOrder: 6,
    heroEmoji: '🎯',
    title: 'What are you into?',
    subtitle: 'Pick at least 3 — travel, shopping & more',
    minSelections: 3,
    maxSelections: null,
    options: [
      { key: 'travel', label: 'Travel', hint: 'Trips & adventures', emoji: '✈️', sortOrder: 1 },
      { key: 'shopping', label: 'Shopping', hint: 'Retail therapy', emoji: '🛍️', sortOrder: 2 },
      { key: 'fitness', label: 'Fitness', hint: 'Gym & active life', emoji: '💪', sortOrder: 3 },
      { key: 'music', label: 'Music', hint: 'Concerts & playlists', emoji: '🎵', sortOrder: 4 },
      { key: 'food', label: 'Food & dining', hint: 'Restaurants & cooking', emoji: '🍽️', sortOrder: 5 },
      { key: 'nightlife', label: 'Nightlife', hint: 'Bars, clubs & events', emoji: '🌃', sortOrder: 6 },
      { key: 'gaming', label: 'Gaming', hint: 'Console, PC & mobile', emoji: '🎮', sortOrder: 7 },
      { key: 'reading', label: 'Reading', hint: 'Books & stories', emoji: '📚', sortOrder: 8 },
      { key: 'art', label: 'Art & design', hint: 'Creative expression', emoji: '🎨', sortOrder: 9 },
      { key: 'outdoors', label: 'Outdoors', hint: 'Nature & hiking', emoji: '🏕️', sortOrder: 10 },
      { key: 'pets', label: 'Pets', hint: 'Dogs, cats & more', emoji: '🐾', sortOrder: 11 },
      { key: 'tech', label: 'Tech', hint: 'Gadgets & startups', emoji: '💻', sortOrder: 12 },
      { key: 'movies', label: 'Movies & TV', hint: 'Binge-worthy nights', emoji: '🎬', sortOrder: 13 },
      { key: 'wellness', label: 'Wellness', hint: 'Mind, body & balance', emoji: '🧘', sortOrder: 14 },
    ],
  },
  {
    stepKey: 'date_of_birth',
    kind: 'input',
    sortOrder: 7,
    heroEmoji: '🎂',
    title: 'What’s your date of birth?',
    subtitle: 'Used for safety and age-appropriate matching',
    minSelections: null,
    maxSelections: null,
    options: [],
  },
];
