import { useEffect, useState } from 'react';
import {
  adminCompanySubscriptionsService,
  type CompanyBillingCycle,
  type CompanySubscription,
  type CompanyInvoice,
  type Currency,
} from '@/services/admin/adminCompanySubscriptionsService';
import { adminHrService, type Employee } from '@/services/admin/adminHrService';
import { getAdminSession } from '@/features/admin/session/adminSession';
import { jsPDF } from 'jspdf';
import { AdminConfirmDialog, AdminHeartLoader, AdminNotificationModal } from '../AdminFeedback';
import './AdminCompanySubscriptions.css';

const emptySubscription = {
  name: '',
  vendor: '',
  description: '',
  amount: '',
  currency: 'ZAR',
  billingCycle: 'monthly' as CompanyBillingCycle,
  nextBillingDate: '',
  accountReference: '',
  usageScope: 'company' as 'company' | 'employee',
  assignedEmployeeId: '',
};

function money(amount: number, currency: string) {
  return new Intl.NumberFormat('en-ZA', { style: 'currency', currency }).format(amount);
}

async function imageDataUrl(path: string): Promise<string> {
  const response = await fetch(path);
  if (!response.ok) throw new Error('Could not load the Lavey logo.');
  const blob = await response.blob();
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result));
    reader.onerror = () => reject(new Error('Could not prepare the Lavey logo.'));
    reader.readAsDataURL(blob);
  });
}

async function buildStoredInvoicePdf(invoice: CompanyInvoice): Promise<jsPDF> {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  const right = pageWidth - margin;
  const amount = money(invoice.amount, invoice.currency);
  const issueDate = new Date(`${invoice.invoiceDate}T00:00:00`).toLocaleDateString('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' });
  const dueDate = invoice.dueDate
    ? new Date(`${invoice.dueDate}T00:00:00`).toLocaleDateString('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' })
    : 'On receipt';

  doc.setFillColor(0, 0, 0);
  doc.rect(margin, 6, pageWidth - margin * 2, 2, 'F');
  doc.addImage(await imageDataUrl('/images/logo.png'), 'PNG', right - 23, 17, 23, 23);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('Invoice', margin + 10, 28);

  doc.setFontSize(9);
  doc.text('Invoice number', margin + 10, 45);
  doc.text('Date of issue', margin + 10, 52);
  doc.text('Date due', margin + 10, 59);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.invoiceNumber, margin + 42, 45);
  doc.text(issueDate, margin + 42, 52);
  doc.text(dueDate, margin + 42, 59);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text(invoice.vendor, margin + 10, 79);
  doc.text('Bill to', 108, 79);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Subscription supplier', margin + 10, 87);
  doc.text(`Reference: ${invoice.invoiceNumber}`, margin + 10, 94);
  doc.text('Lavey', 108, 87);
  doc.text('Company billing workspace', 108, 94);
  doc.text(`Used by: ${invoice.usedByName}`, 108, 101);
  doc.text(`Generated by: ${invoice.generatedByName}`, 108, 108);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(`${amount} due ${dueDate}`, margin + 10, 128);

  const tableTop = 150;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text('Description', margin + 10, tableTop);
  doc.text('Qty', 130, tableTop, { align: 'right' });
  doc.text('Unit price', 158, tableTop, { align: 'right' });
  doc.text('Amount', right - 10, tableTop, { align: 'right' });
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.45);
  doc.line(margin + 10, tableTop + 4, right - 10, tableTop + 4);

  const descriptionLines = doc.splitTextToSize(invoice.description, 95) as string[];
  doc.setFontSize(9);
  doc.text(descriptionLines, margin + 10, tableTop + 13);
  doc.text('1', 130, tableTop + 13, { align: 'right' });
  doc.text(amount, 158, tableTop + 13, { align: 'right' });
  doc.text(amount, right - 10, tableTop + 13, { align: 'right' });

  const summaryTop = Math.max(190, tableTop + 22 + descriptionLines.length * 5);
  doc.setDrawColor(210, 210, 210);
  doc.setLineWidth(0.25);
  doc.line(105, summaryTop, right - 10, summaryTop);
  doc.text('Subtotal', 105, summaryTop + 7);
  doc.text(amount, right - 10, summaryTop + 7, { align: 'right' });
  doc.line(105, summaryTop + 10, right - 10, summaryTop + 10);
  doc.text('Tax', 105, summaryTop + 17);
  doc.text('Included', right - 10, summaryTop + 17, { align: 'right' });
  doc.line(105, summaryTop + 20, right - 10, summaryTop + 20);
  doc.setFont('helvetica', 'bold');
  doc.text('Total', 105, summaryTop + 27);
  doc.text(amount, right - 10, summaryTop + 27, { align: 'right' });
  doc.line(105, summaryTop + 30, right - 10, summaryTop + 30);
  doc.text('Amount due', 105, summaryTop + 37);
  doc.text(`${amount} ${invoice.currency}`, right - 10, summaryTop + 37, { align: 'right' });

  if (invoice.notes) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.text('Notes', margin + 10, 244);
    doc.setFont('helvetica', 'normal');
    doc.text(doc.splitTextToSize(invoice.notes, 110), margin + 10, 251);
  }
  doc.setTextColor(100, 100, 100);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.text('Generated from the Lavey company billing register.', margin + 10, 282);
  doc.text(`Status: ${invoice.status}`, right - 10, 282, { align: 'right' });
  return doc;
}

export function AdminCompanySubscriptions() {
  const signedInAdmin = getAdminSession()?.admin;
  const defaultGenerator = signedInAdmin?.displayName || signedInAdmin?.email || 'Admin';
  const [subscriptions, setSubscriptions] = useState<CompanySubscription[]>([]);
  const [invoices, setInvoices] = useState<CompanyInvoice[]>([]);
  const [deletedInvoices, setDeletedInvoices] = useState<CompanyInvoice[]>([]);
  const [showInvoiceBin, setShowInvoiceBin] = useState(false);
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [currencies, setCurrencies] = useState<Currency[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [invoicePendingDelete, setInvoicePendingDelete] = useState<CompanyInvoice | null>(null);
  const [deletingInvoice, setDeletingInvoice] = useState(false);
  const [showAdd, setShowAdd] = useState(false);
  const [form, setForm] = useState(emptySubscription);
  const [selectedId, setSelectedId] = useState('');
  const [invoice, setInvoice] = useState({
    invoiceNumber: `LVY-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`,
    invoiceDate: new Date().toISOString().slice(0, 10),
    dueDate: '',
    vendor: '',
    description: '',
    amount: '',
    currency: 'ZAR',
    notes: '',
    generatedBy: defaultGenerator,
    usedBy: 'Whole company',
  });

  const load = async () => {
    setLoading(true);
    setError('');
    try {
      const [subscriptionRows, employeeRows, invoiceRows, currencyRows] = await Promise.all([
        adminCompanySubscriptionsService.list(),
        adminHrService.listEmployees(),
        adminCompanySubscriptionsService.listInvoices(),
        adminCompanySubscriptionsService.listCurrencies(),
      ]);
      setSubscriptions(subscriptionRows);
      setEmployees(employeeRows.filter((employee) => employee.employmentStatus !== 'terminated'));
      setInvoices(invoiceRows);
      setCurrencies(currencyRows);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not load company subscriptions.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { void load(); }, []);

  const selectSubscription = (id: string) => {
    setSelectedId(id);
    const item = subscriptions.find((subscription) => subscription.id === id);
    if (!item) return;
    setInvoice((current) => ({
      ...current,
      vendor: item.vendor,
      description: `${item.name}${item.description ? ` — ${item.description}` : ''}`,
      amount: String(item.amount),
      currency: item.currency,
      dueDate: item.nextBillingDate ?? current.dueDate,
      usedBy: item.usageScope === 'company'
        ? 'Whole company'
        : item.assignedEmployeeName || 'Assigned employee',
    }));
  };

  const addSubscription = async () => {
    setError('');
    try {
      const created = await adminCompanySubscriptionsService.create({
        name: form.name,
        vendor: form.vendor,
        description: form.description,
        amount: Number(form.amount),
        currency: form.currency,
        billingCycle: form.billingCycle,
        status: 'active',
        nextBillingDate: form.nextBillingDate || null,
        accountReference: form.accountReference || null,
        usageScope: form.usageScope,
        assignedEmployeeId: form.usageScope === 'employee' ? form.assignedEmployeeId : null,
        assignedEmployeeName: form.usageScope === 'employee'
          ? employees.find((employee) => employee.id === form.assignedEmployeeId)?.fullName ?? null
          : null,
      });
      setSubscriptions((current) => [created, ...current]);
      setForm(emptySubscription);
      setShowAdd(false);
      setNotice('Company subscription added.');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not add subscription.');
    }
  };

  const toggleStatus = async (item: CompanySubscription) => {
    const status = item.status === 'active' ? 'paused' : 'active';
    try {
      const updated = await adminCompanySubscriptionsService.update(item.id, { status });
      setSubscriptions((current) => current.map((value) => value.id === item.id ? updated : value));
      setNotice(`${item.name} ${status}.`);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not update subscription.');
    }
  };

  const openStoredInvoice = async (item: CompanyInvoice, download: boolean) => {
    setError('');
    const previewWindow = download ? null : window.open('', '_blank');
    try {
      const doc = await buildStoredInvoicePdf(item);
      const fileName = `invoice-${item.invoiceNumber.replace(/[^a-z0-9-]/gi, '-')}.pdf`;
      if (download) {
        doc.save(fileName);
      } else {
        const url = URL.createObjectURL(doc.output('blob'));
        if (previewWindow) {
          previewWindow.opener = null;
          previewWindow.location.href = url;
        } else {
          throw new Error('Your browser blocked the invoice preview. Allow pop-ups and try again.');
        }
        window.setTimeout(() => URL.revokeObjectURL(url), 60_000);
      }
    } catch (err) {
      previewWindow?.close();
      setError(err instanceof Error ? err.message : 'Could not open the submitted invoice.');
    }
  };

  const deleteStoredInvoice = (item: CompanyInvoice) => {
    setInvoicePendingDelete(item);
  };

  const confirmDeleteStoredInvoice = async () => {
    if (!invoicePendingDelete) return;
    const item = invoicePendingDelete;
    setDeletingInvoice(true);
    try {
      await adminCompanySubscriptionsService.deleteInvoice(item.id);
      const deletedAt = new Date().toISOString();
      setInvoices((current) => current.filter((invoice) => invoice.id !== item.id));
      setDeletedInvoices((current) => [{
        ...item,
        deletedAt,
        permanentDeleteAt: new Date(Date.now() + 10 * 86_400_000).toISOString(),
      }, ...current]);
      setInvoicePendingDelete(null);
      setNotice(`${item.invoiceNumber} moved to the invoice bin.`);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not delete the invoice.');
    } finally {
      setDeletingInvoice(false);
    }
  };

  const openInvoiceBin = async () => {
    const next = !showInvoiceBin;
    setShowInvoiceBin(next);
    if (!next) return;
    try {
      setDeletedInvoices(await adminCompanySubscriptionsService.listDeletedInvoices());
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not load the invoice bin.');
    }
  };

  const restoreStoredInvoice = async (item: CompanyInvoice) => {
    try {
      const restored = await adminCompanySubscriptionsService.restoreInvoice(item.id);
      setDeletedInvoices((current) => current.filter((invoice) => invoice.id !== item.id));
      setInvoices((current) => [restored, ...current]);
      setNotice(`${item.invoiceNumber} restored.`);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not restore the invoice.');
    }
  };

  const generateInvoice = async () => {
    if (!invoice.vendor || !invoice.description || !invoice.amount) {
      setError('Add a vendor, description, and amount before generating the invoice.');
      return;
    }
    setError('');
    try {
      const submitted = await adminCompanySubscriptionsService.createInvoice({
        subscriptionId: selectedId || null,
        invoiceNumber: invoice.invoiceNumber,
        invoiceDate: invoice.invoiceDate,
        dueDate: invoice.dueDate || null,
        vendor: invoice.vendor,
        description: invoice.description,
        amount: Number(invoice.amount),
        currency: invoice.currency,
        generatedByName: invoice.generatedBy,
        usedByName: invoice.usedBy,
        notes: invoice.notes,
      });
      setInvoices((current) => [submitted, ...current]);
      const formalInvoice = await buildStoredInvoicePdf(submitted);
      formalInvoice.save(`invoice-${invoice.invoiceNumber.replace(/[^a-z0-9-]/gi, '-')}.pdf`);
      setNotice('Invoice submitted to the company register and downloaded as PDF.');
      return;

      /*
       * Retired coloured invoice template retained temporarily for migration history.
       * New invoices use buildStoredInvoicePdf above so stored and generated files match.
      const doc = new jsPDF({ unit: 'mm', format: 'a4' });
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 18;
      const right = pageWidth - margin;
      const pink: [number, number, number] = [239, 71, 111];
      const navy: [number, number, number] = [15, 23, 42];
      const slate: [number, number, number] = [100, 116, 139];
      const pale: [number, number, number] = [248, 250, 252];
      const amount = money(Number(invoice.amount), invoice.currency);
      const dueAt = invoice.dueDate ? new Date(`${invoice.dueDate}T23:59:59`) : null;
      const daysUntilDue = dueAt ? Math.ceil((dueAt.getTime() - Date.now()) / 86_400_000) : null;
      const paymentStatus = daysUntilDue === null
        ? 'PAYABLE'
        : daysUntilDue < 0
          ? 'OVERDUE'
          : daysUntilDue <= 7
            ? 'DUE SOON'
            : 'SCHEDULED';

      doc.setFillColor(...navy);
      doc.rect(0, 0, pageWidth, 8, 'F');
      const logo = await imageDataUrl('/images/logo.png');
      doc.addImage(logo, 'PNG', margin, 15, 25, 25);
      doc.setTextColor(...navy);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(24);
      doc.text('Lavey', 47, 27);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...slate);
      doc.setFontSize(9);
      doc.text('COMPANY SUBSCRIPTION BILLING', 47, 33);

      doc.setTextColor(...navy);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(25);
      doc.text('INVOICE', right, 24, { align: 'right' });
      doc.setFontSize(10);
      doc.text(`# ${invoice.invoiceNumber}`, right, 31, { align: 'right' });
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...slate);
      doc.setFontSize(9);
      doc.text(`Issued ${invoice.invoiceDate}`, right, 36, { align: 'right' });
      if (invoice.dueDate) doc.text(`Due ${invoice.dueDate}`, right, 41, { align: 'right' });
      doc.setTextColor(...pink);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.5);
      doc.text(paymentStatus, right, 46, { align: 'right' });

      doc.setDrawColor(...pink);
      doc.setLineWidth(1.2);
      doc.line(margin, 48, right, 48);

      doc.setFillColor(...pale);
      doc.roundedRect(margin, 57, pageWidth - margin * 2, 35, 3, 3, 'F');
      doc.setTextColor(...slate);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.text('PAYABLE TO', margin + 7, 67);
      doc.setTextColor(...navy);
      doc.setFontSize(17);
      doc.text(invoice.vendor, margin + 7, 76);
      if (selected?.accountReference) {
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...slate);
        doc.setFontSize(9);
        doc.text(`Account reference: ${selected.accountReference}`, margin + 7, 84);
      }

      doc.setTextColor(...slate);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.text('SUBSCRIPTION USED BY', margin, 105);
      doc.text('INVOICE GENERATED BY', 108, 105);
      doc.setTextColor(...navy);
      doc.setFontSize(11);
      doc.text(invoice.usedBy, margin, 112);
      doc.text(invoice.generatedBy, 108, 112);

      doc.setFillColor(...navy);
      doc.roundedRect(margin, 124, pageWidth - margin * 2, 10, 2, 2, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.text('DESCRIPTION', margin + 5, 130.5);
      doc.text('AMOUNT', right - 5, 130.5, { align: 'right' });

      const descriptionLines = doc.splitTextToSize(invoice.description, 125) as string[];
      const rowHeight = Math.max(25, 13 + descriptionLines.length * 5);
      doc.setTextColor(...navy);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.text(descriptionLines, margin + 5, 145);
      doc.setFont('helvetica', 'bold');
      doc.text(amount, right - 5, 145, { align: 'right' });
      doc.setDrawColor(226, 232, 240);
      doc.line(margin, 134 + rowHeight, right, 134 + rowHeight);

      const totalY = 148 + rowHeight;
      doc.setTextColor(...slate);
      doc.setFontSize(9);
      doc.text('SUBTOTAL', 130, totalY);
      doc.setTextColor(...navy);
      doc.text(amount, right, totalY, { align: 'right' });
      doc.setTextColor(...slate);
      doc.text('TAX', 130, totalY + 8);
      doc.setTextColor(...navy);
      doc.text('Included', right, totalY + 8, { align: 'right' });
      doc.setFillColor(...pink);
      doc.roundedRect(125, totalY + 14, right - 125, 17, 2, 2, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(11);
      doc.text('TOTAL', 130, totalY + 24.5);
      doc.setFontSize(14);
      doc.text(amount, right - 5, totalY + 24.5, { align: 'right' });

      if (invoice.notes) {
        const notesY = Math.min(totalY + 45, 237);
        doc.setTextColor(...navy);
        doc.setFontSize(9);
        doc.text('NOTES', margin, notesY);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...slate);
        doc.text(doc.splitTextToSize(invoice.notes, 170), margin, notesY + 7);
      }

      doc.setDrawColor(226, 232, 240);
      doc.line(margin, 270, right, 270);
      doc.setTextColor(...slate);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.text('Generated securely from the Lavey admin company billing workspace.', margin, 277);
      doc.text(`Document ${invoice.invoiceNumber}`, right, 277, { align: 'right' });
      doc.setTextColor(...pink);
      doc.text('lavey.co.za', margin, 283);

      doc.save(`invoice-${invoice.invoiceNumber.replace(/[^a-z0-9-]/gi, '-')}.pdf`);
      setNotice('Invoice submitted to the company register and downloaded as PDF.');
      */
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not generate the PDF invoice.');
    }
  };

  return (
    <section className="company-billing" aria-label="Company subscriptions and invoices">
      <div className="company-billing__header">
        <div><h3>Company subscriptions</h3><p>Track recurring services paid for by the company.</p></div>
        <button className="admin-hr-hub__btn admin-hr-hub__btn--primary" type="button" onClick={() => setShowAdd((value) => !value)}>
          {showAdd ? 'Cancel' : '+ Add subscription'}
        </button>
      </div>
      {error ? <p className="admin-hr-hub__error">{error}</p> : null}
      {showAdd ? (
        <form className="company-billing__form" onSubmit={(event) => { event.preventDefault(); void addSubscription(); }}>
          <label>Subscription name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="e.g. Figma Professional" /></label>
          <label>Vendor<input required value={form.vendor} onChange={(e) => setForm({ ...form, vendor: e.target.value })} placeholder="Supplier name" /></label>
          <label>Amount<input required min="0" step="0.01" type="number" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></label>
          <label>Currency<select required value={form.currency} onChange={(e) => setForm({ ...form, currency: e.target.value })}>{currencies.map((c) => <option key={c.code} value={c.code}>{c.code} — {c.name}</option>)}</select></label>
          <label>Billing cycle<select value={form.billingCycle} onChange={(e) => setForm({ ...form, billingCycle: e.target.value as CompanyBillingCycle })}><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="yearly">Yearly</option><option value="one_time">One time</option></select></label>
          <label>Next billing date<input type="date" value={form.nextBillingDate} onChange={(e) => setForm({ ...form, nextBillingDate: e.target.value })} /></label>
          <label>Account reference<input value={form.accountReference} onChange={(e) => setForm({ ...form, accountReference: e.target.value })} /></label>
          <label className="company-billing__wide">Used by
            <select value={form.usageScope === 'company' ? 'company' : form.assignedEmployeeId} onChange={(e) => setForm({ ...form, usageScope: e.target.value === 'company' ? 'company' : 'employee', assignedEmployeeId: e.target.value === 'company' ? '' : e.target.value })}>
              <option value="company">Whole company</option>
              {employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.fullName} — {employee.department}</option>)}
            </select>
          </label>
          <label className="company-billing__wide">Description<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label>
          <button className="admin-hr-hub__btn admin-hr-hub__btn--primary" type="submit">Save subscription</button>
        </form>
      ) : null}

      <div className="company-billing__cards">
        {loading ? <p>Loading subscriptions…</p> : null}
        {!loading && subscriptions.length === 0 ? <div className="company-billing__empty">No company subscriptions yet. Add the first one above.</div> : null}
        {subscriptions.map((item) => (
          <article key={item.id}>
            <div><span className={`company-billing__status is-${item.status}`}>{item.status}</span><h4>{item.name}</h4><p>{item.vendor}</p></div>
            <strong>{money(item.amount, item.currency)} <small>/ {item.billingCycle.replace('_', ' ')}</small></strong>
            <span>Used by: {item.usageScope === 'company' ? 'Whole company' : item.assignedEmployeeName || 'Employee'}</span>
            <span>{item.nextBillingDate ? `Next payment ${new Date(`${item.nextBillingDate}T00:00:00`).toLocaleDateString()}` : 'No billing date'}</span>
            <button type="button" onClick={() => void toggleStatus(item)}>{item.status === 'active' ? 'Pause' : 'Activate'}</button>
          </article>
        ))}
      </div>

      <section className="company-billing__invoice">
        <div className="company-billing__header"><div><h3>Generate invoice</h3><p>Select a saved subscription to pre-fill the invoice, or enter a once-off company expense.</p></div></div>
        <div className="company-billing__form">
          <label className="company-billing__wide">Subscription<select value={selectedId} onChange={(e) => selectSubscription(e.target.value)}><option value="">No subscription — manual invoice</option>{subscriptions.map((item) => <option key={item.id} value={item.id}>{item.name} — {item.vendor}</option>)}</select></label>
          <label>Invoice number<input value={invoice.invoiceNumber} onChange={(e) => setInvoice({ ...invoice, invoiceNumber: e.target.value })} /></label>
          <label>Invoice date<input type="date" value={invoice.invoiceDate} onChange={(e) => setInvoice({ ...invoice, invoiceDate: e.target.value })} /></label>
          <label>Due date<input type="date" value={invoice.dueDate} onChange={(e) => setInvoice({ ...invoice, dueDate: e.target.value })} /></label>
          <label>Vendor<input value={invoice.vendor} onChange={(e) => setInvoice({ ...invoice, vendor: e.target.value })} /></label>
          <label>Amount<input min="0" step="0.01" type="number" value={invoice.amount} onChange={(e) => setInvoice({ ...invoice, amount: e.target.value })} /></label>
          <label>Currency<select value={invoice.currency} onChange={(e) => setInvoice({ ...invoice, currency: e.target.value })}>{currencies.map((c) => <option key={c.code} value={c.code}>{c.code} — {c.name}</option>)}</select></label>
          <label>Generated by
            <select value={invoice.generatedBy} onChange={(e) => setInvoice({ ...invoice, generatedBy: e.target.value })}>
              <option value={defaultGenerator}>{defaultGenerator} — signed-in admin</option>
              {employees
                .filter((employee) => employee.fullName !== defaultGenerator)
                .map((employee) => (
                  <option key={employee.id} value={employee.fullName}>
                    {employee.fullName} — {employee.department}
                  </option>
                ))}
            </select>
          </label>
          <label>Subscription used by<select value={invoice.usedBy} onChange={(e) => setInvoice({ ...invoice, usedBy: e.target.value })}><option value="Whole company">Whole company</option>{employees.map((employee) => <option key={employee.id} value={employee.fullName}>{employee.fullName} — {employee.department}</option>)}</select></label>
          <label className="company-billing__wide">Description<input value={invoice.description} onChange={(e) => setInvoice({ ...invoice, description: e.target.value })} /></label>
          <label className="company-billing__wide">Notes<textarea value={invoice.notes} onChange={(e) => setInvoice({ ...invoice, notes: e.target.value })} /></label>
          <button className="admin-hr-hub__btn admin-hr-hub__btn--primary" type="button" onClick={() => void generateInvoice()}>Generate &amp; submit invoice</button>
        </div>
      </section>

      <section className="company-billing__invoice">
        <div className="company-billing__header">
          <div><h3>Company invoice register</h3><p>Submitted internal invoices available for payment claims and company records.</p></div>
          <button type="button" className="company-billing__bin-button" onClick={() => void openInvoiceBin()}>
            {showInvoiceBin ? 'Close invoice bin' : `Invoice bin${deletedInvoices.length ? ` (${deletedInvoices.length})` : ''}`}
          </button>
        </div>
        <div className="admin-hr-hub__table-wrap">
          <table className="admin-hr-hub__table">
            <thead><tr><th>Invoice</th><th>Vendor</th><th>Used by</th><th>Due</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead>
            <tbody>
              {invoices.map((item) => (
                <tr key={item.id}>
                  <td><strong>{item.invoiceNumber}</strong><br /><small>{item.invoiceDate}</small></td>
                  <td>{item.vendor}</td>
                  <td>{item.usedByName}</td>
                  <td>{item.dueDate || '—'}</td>
                  <td><strong>{money(item.amount, item.currency)}</strong></td>
                  <td><span className={`company-billing__status is-${item.status}`}>{item.status}</span></td>
                  <td>
                    <div className="company-billing__invoice-actions">
                      <button type="button" onClick={() => void openStoredInvoice(item, false)}>View</button>
                      <button type="button" onClick={() => void openStoredInvoice(item, true)}>Download PDF</button>
                      <button type="button" className="is-danger" onClick={() => void deleteStoredInvoice(item)}>Delete</button>
                    </div>
                  </td>
                </tr>
              ))}
              {invoices.length === 0 ? <tr><td colSpan={7}>No submitted invoices yet.</td></tr> : null}
            </tbody>
          </table>
        </div>
        {showInvoiceBin ? (
          <div className="company-billing__bin">
            <div><strong>Invoice bin</strong><p>Invoices are permanently deleted 10 days after being moved here.</p></div>
            {deletedInvoices.length === 0 ? <p className="company-billing__empty">The invoice bin is empty.</p> : (
              <div className="admin-hr-hub__table-wrap">
                <table className="admin-hr-hub__table">
                  <thead><tr><th>Invoice</th><th>Vendor</th><th>Deleted</th><th>Permanent deletion</th><th>Action</th></tr></thead>
                  <tbody>{deletedInvoices.map((item) => (
                    <tr key={item.id}>
                      <td><strong>{item.invoiceNumber}</strong></td>
                      <td>{item.vendor}</td>
                      <td>{item.deletedAt ? new Date(item.deletedAt).toLocaleString('en-ZA') : '—'}</td>
                      <td>{item.permanentDeleteAt ? new Date(item.permanentDeleteAt).toLocaleString('en-ZA') : '—'}</td>
                      <td><button type="button" className="company-billing__restore" onClick={() => void restoreStoredInvoice(item)}>Restore</button></td>
                    </tr>
                  ))}</tbody>
                </table>
              </div>
            )}
          </div>
        ) : null}
      </section>
      {loading ? <AdminHeartLoader label="Loading company billing" overlay /> : null}
      <AdminConfirmDialog
        open={Boolean(invoicePendingDelete)}
        title="Move invoice to bin?"
        message={invoicePendingDelete ? `Are you sure you want to move invoice ${invoicePendingDelete.invoiceNumber} to the bin? It will be permanently deleted after 10 days.` : ''}
        confirmLabel="Move to bin"
        tone="danger"
        busy={deletingInvoice}
        onCancel={() => setInvoicePendingDelete(null)}
        onConfirm={() => void confirmDeleteStoredInvoice()}
      />
      <AdminNotificationModal
        open={Boolean(notice)}
        message={notice}
        tone="success"
        autoCloseMs={4000}
        onClose={() => setNotice('')}
      />
    </section>
  );
}
