name: Build and submit Android

on:
  push:
    branches: ['release/android']

jobs:
  build_android:
    name: Build production AAB
    type: build
    environment: production
    params:
      platform: android
      profile: production

  submit_android:
    name: Submit to Google Play internal testing
    needs: [build_android]
    type: submit
    params:
      profile: production
      build_id: ${{ needs.build_android.outputs.build_id }}
