// Static UI text for SettingsScreen.tsx, translated via useTranslatedStrings.
// Keep this in sync with the screen's JSX — do NOT add dynamic values here
// (email addresses, the user's name, the "Lavey mobile · x.y.z" version string).
export const SETTINGS_SCREEN_STRINGS = [
  "Settings",
  "PROFILE",
  "Edit profile",
  "Name, bio, education, work & interests",
  "Identity verified",
  "Verify my identity",
  "Build trust with a verified badge",
  "Update my location",
  "Improve nearby recommendations",
  "Theme song",
  "Choose a song for your profile",
  "PREFERENCES",
  "App language",
  "Language used across Lavey",
  "AI-translated (beta) — may be imperfect",
  "Push notifications",
  "New matches, messages and gift activity",
  "Like feedback sound",
  "Play a soft chime when you like someone",
  "ACCOUNT",
  "Email",
  "Change password",
  "Update your account password",
  "You signed in with Google. Manage your password in your Google account.",
  "Upgrade to Platinum",
  "More ways to connect and stand out",
  "Safety, privacy & take a break",
  "Visibility, contacts, blocks and your data",
  "HELP & TRUST",
  "Contact support",
  "Chat with Lavey AI or talk to our team",
  "Community guidelines",
  "How we keep Lavey respectful and safe",
  "Terms of service",
  "Your rights, privacy and how Lavey works",
  "Log out",
  "Sign out of this device",
  "Choose your language",
  "Select the language you want to use in Lavey.",
  "Beta languages are AI-translated and may not be perfectly accurate yet.",
  "Change your password",
  "Enter your current password, then choose a new one.",
  "Current password",
  "New password (8+ characters)",
  "Update password",
  "Cancel",
  "Log out?",
  "You can sign back in anytime with the same account.",
] as const;
