/**
 * API route definitions. Keep paths in one place for easy backend alignment.
 */
export const API_ENDPOINTS = {
  translation: {
    ui: '/translation/ui',
  },
  auth: {
    google: '/auth/google',
    googleCallback: '/auth/google/callback',
    login: '/auth/login',
    register: '/auth/register',
    verifyEmail: '/auth/verify-email',
    resendVerification: '/auth/resend-verification',
    me: '/auth/me',
    logout: '/auth/logout',
    changePassword: '/auth/change-password',
  },
  profiles: {
    discover: '/profiles/discover',
    byId: (id: string) => `/profiles/${id}`,
    recordView: (id: string) => `/profiles/${id}/view`,
  },
  paidChat: {
    catalog: '/discovery/chat-credits',
    checkout: '/discovery/chat-credits/checkout',
    checkoutStatus: (paymentId: string) => `/discovery/chat-credits/checkouts/${encodeURIComponent(paymentId)}`,
    unlock: (profileId: string) => `/discovery/chat-unlocks/${profileId}`,
  },
  matches: {
    flame: '/matches/flame',
    list: '/matches',
    greetings: '/matches/greetings',
    iCrush: '/matches/i-crush',
    iCrushAccept: (inviteId: string) => `/matches/i-crush/${inviteId}/accept`,
    iCrushReject: (inviteId: string) => `/matches/i-crush/${inviteId}/reject`,
  },
  subscription: {
    flameQuota: '/subscription/flame-quota',
    platinum: '/subscription/platinum',
    platinumCheckout: '/subscription/platinum/checkout',
    platinumStatus: '/subscription/platinum/status',
    platinumConfirmReturn: '/subscription/platinum/confirm-return',
    platinumCancel: '/subscription/platinum/cancel',
  },
  messages: {
    conversations: '/messages/conversations',
    conversationByProfile: (profileId: string) => `/messages/conversations/by-profile/${profileId}`,
    thread: (id: string) => `/messages/conversations/${id}`,
    sendMessage: (id: string) => `/messages/conversations/${id}/messages`,
    sendPhoto: (id: string) => `/messages/conversations/${id}/photos`,
    sendAudio: (id: string) => `/messages/conversations/${id}/audio`,
    activeVideoCall: '/messages/video-calls/active',
    startVideoCall: (id: string) => `/messages/conversations/${id}/video-calls`,
    updateVideoCall: (callId: string) => `/messages/video-calls/${callId}`,
    markRead: (id: string) => `/messages/conversations/${id}/read`,
    typing: (id: string) => `/messages/conversations/${id}/typing`,
    delete: (id: string) => `/messages/conversations/${id}`,
    pin: (id: string) => `/messages/conversations/${id}/pin`,
    presence: '/messages/presence',
    message: (conversationId: string, messageId: string) =>
      `/messages/conversations/${conversationId}/messages/${messageId}`,
    chatAssist: (conversationId: string) =>
      `/messages/conversations/${conversationId}/chat-assist`,
    notifications: '/messages/notifications',
    notificationsSummary: '/messages/notifications/summary',
    notificationsRead: '/messages/notifications/read',
    officialInbox: '/messages/official-inbox',
    officialInboxRead: '/messages/official-inbox/read',
  },
  dates: {
    list: '/rooms/vibe-check',
    create: '/dates',
    byId: (id: string) => `/dates/${id}`,
    hostProfile: (id: string) => `/dates/${id}/host-profile`,
    invites: '/dates/invites',
    respondToInvite: (id: string) => `/dates/invites/${id}`,
    joinByCode: '/dates/join-by-code',
    join: (id: string) => `/rooms/vibe-check/${id}/join`,
    like: (id: string) => `/rooms/vibe-check/${id}/like`,
  },
  users: {
    me: '/users/me',
    verification: '/users/me/verification',
    location: '/users/me/location',
    onboarding: '/users/me/onboarding',
    privacy: '/users/me/privacy',
    settings: '/users/me/settings',
    blocked: '/users/me/blocked',
    blockUser: (userId: string) => `/users/me/blocked/${userId}`,
    contactsImport: '/users/me/contacts/import',
    contactsSearch: '/users/me/contacts/search',
    dataExport: '/users/me/data-export',
    deleteAccount: '/users/me',
    pushVapidPublicKey: '/users/me/push/vapid-public-key',
    pushSubscribe: '/users/me/push/subscribe',
    pushTest: '/users/me/push/test',
  },
  content: {
    posts: '/users/me/posts',
    postById: (id: string) => `/users/me/posts/${id}`,
    postLikes: (id: string) => `/users/me/posts/${id}/likes`,
    receivedPostLikes: '/users/me/received-post-likes',
    avatar: '/users/me/avatar',
    photoCompliment: '/users/me/photo-compliment',
  },
  posts: {
    like: (postId: string) => `/posts/${postId}/like`,
  },
  onboarding: {
    questions: '/onboarding/questions',
    interests: '/onboarding/interests',
  },
  gifts: {
    send: '/gifts',
    payoutCatalog: '/gifts/payout-catalog',
    wallet: '/users/me/gifts/wallet',
    activity: '/users/me/gifts/activity',
    payoutAccount: '/users/me/gifts/payout-account',
    withdraw: '/users/me/gifts/withdraw',
  },
  admin: {
    auth: {
      registrationStatus: '/admin/auth/registration-status',
      register: '/admin/auth/register',
      login: '/admin/auth/login',
      me: '/admin/auth/me',
    },
    users: '/admin/users',
    userById: (id: string) => `/admin/users/${id}`,
    userLikers: (id: string) => `/admin/users/${id}/likers`,
    userMatches: (id: string) => `/admin/users/${id}/matches`,
    userMeetings: (id: string) => `/admin/users/${id}/meetings`,
    userInsight: (id: string) => `/admin/users/${id}/insight`,
    userAction: (id: string) => `/admin/users/${id}/action`,
    userResetPassword: (id: string) => `/admin/users/${id}/reset-password`,
    userMessage: (id: string) => `/admin/users/${id}/message`,
    supportTickets: '/admin/support/tickets',
    supportTicket: (id: string) => `/admin/support/tickets/${id}`,
    supportTicketMessages: (id: string) => `/admin/support/tickets/${id}/messages`,
    moderationStats: '/admin/moderation/stats',
    moderationQueue: '/admin/moderation/queue',
    moderationReports: '/admin/moderation/reports',
    moderationQueueAction: (id: string) => `/admin/moderation/queue/${id}/action`,
    moderationReportAction: (id: string) => `/admin/moderation/reports/${id}/action`,
    moderationPolicy: '/admin/moderation/policy',
    moderationRescan: '/admin/moderation/rescan',
    algorithms: '/admin/algorithms',
    algorithmsOverview: '/admin/algorithms/overview',
    algorithmsActive: '/admin/algorithms/active',
    algorithmTrend: (slug: string) => `/admin/algorithms/${slug}/trend`,
    algorithmActivate: (slug: string) => `/admin/algorithms/${slug}/activate`,
    hrOverview: '/admin/hr/overview',
    hrRoles: '/admin/hr/roles',
    hrRoleById: (id: string) => `/admin/hr/roles/${id}`,
    hrEmployees: '/admin/hr/employees',
    hrEmployeeById: (id: string) => `/admin/hr/employees/${id}`,
    hrClaims: '/admin/hr/claims',
    hrClaimAnalyzeDocument: '/admin/hr/claims/analyze-document',
    hrClaimReview: (id: string) => `/admin/hr/claims/${id}/review`,
    opsOverview: '/admin/ops/overview',
    opsActivity: '/admin/ops/activity',
    opsAlerts: '/admin/ops/alerts',
    opsBroadcasts: '/admin/ops/broadcasts',
    opsAnalytics: '/admin/ops/analytics',
    opsExport: (type: string) => `/admin/ops/export/${type}`,
    opsMonetizationWallets: '/admin/ops/monetization/wallets',
    opsMonetizationWallet: (userId: string) => `/admin/ops/monetization/wallets/${userId}`,
    opsMonetizationGift: (userId: string) => `/admin/ops/monetization/wallets/${userId}/gift`,
  },
  reports: {
    submit: '/reports',
  },
  support: {
    config: '/support/config',
    conversation: '/support/conversation',
    messages: '/support/messages',
  },
  legal: {
    terms: '/legal/terms',
    guidelines: '/legal/guidelines',
  },
  meetings: {
    turnCredentials: '/meetings/turn-credentials',
    liveTranscript: '/meetings/live-transcript',
    attend: (meetupId: string) => `/meetings/${meetupId}/attend`,
  },
} as const;
